import type { Metadata } from "next"
import { Noto_Sans_JP } from "next/font/google"
import "@/app/globals.css"
import { ThemeProvider } from "@/components/theme-provider"
import Header from "@/components/layouts/Header"
import Footer from "@/components/layouts/Footer"

const NOTO_SANS_JP = Noto_Sans_JP({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ja">
      <body className={NOTO_SANS_JP.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          storageKey="theme"
        >
          <Header />
          <main className="mt-[72px] mb-[40px] p-4">{children}</main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}
